env:
  global:
    - secure: 1ZLPNxihMQag8KmaIvHQy3ZSiCJ8R9x3RsNHza8D8upvZWTcg0KFQtwwBygeu5xQ8vk91FaG1K8uLEHZOsWTETHY7IG1toIdTmUVZQxsdj+tZo1CdSqS5HUiWK9Rr6fyZ0hs6yxer0clou3DV1doXO9sVGV4rCPSYgFAwSZ0Mvw/syxE+rZkt7To8INBGQERqcJ7FvBn6AM2cY31W+AKMU7+UnYsN9un7vAnawcmdPwmvS01QzxIR2d+yPTl9CreNE6eAn/MzOvjH0/sYtqXCmMVg5P3cnpF2dY6tBcMUcpMMGbv6QLCU7y4wVjy9vg3Foryo9vknUBo7zDYQQdkO5Vd21U6tYYU0ORTGRVqSMewGKbJG5J5ieWB+84yr+P+Yaufc3fgWsgnYn3WVyaz/s4n5cHvYCJwOlNxCnl2ii9NbkW/RSJZfIBddcrxx6b1PGS3cHN66NWUrNwCI6/5YbR1fEBKtaN7ioCZdd/s/7XiKQbjeWy0cPdfO4TSq4MlZuOpmtngDclu9GNHpcToRF6YhpThR5wSy/vCy1wwj4lS25IIi6UCxFyqhYZYTj+0FIJG2wYyfM+ftYzYlGqAXnVKP7Ud0c7smn8wj+5o0j/ceubbuyc99ZkvJfmq7Yv6eW0ZdxmZ82ibuAwZUMU/tUnHKsE4scq9P8XBGTB3EUQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
