env:
  global:
    - secure: HM/HBx0wtbYvaBgXJmi8keLPB6bHW2QS0ITOEyol45LRsgswy4sb4lSvbbU1z/Pl5rBqaLGGdpHYpbycMp5aB7OG3W3J452xC3OYf8on1q/9spCbEfOCQ7FrJYAcm1Qhb7St3580A7LT4M9xusTwGIDoqa/67WqVRMJJqgkKuguzIug9DzUDQmlnM36627r3mLta6dr61kyUvi9l46hO1bzGsVLnNal4XBVkKwFw1DzTMgvnRPx9XfBtaMTsScn9GkdXucqJoquMTkyfH7ygIIDQ2S6aDLdTCsPdYPyzGReHvk8EoWsqDQjmj3NsxRH/skMMnwY+JPaCNHvHj60DxtM+XchHUbAUjW0fv5lFbxlq9vVAIO5pcc5Ire+zxrKmP+8WCCOPzxqytqoSGf+tQnSOeTM5eawGzp34vk4PYSpuHESWBTcrTuqmKMOF/Tt/VgF/6PvsqjDVrrAhXkv+vYlNxufigfPREGGTbWSxZGBnUSfYIQpxjg3YlRANhggR+Lgem36oREZSa9wyztqs0r1+KwJsjI+Dis3twcrY+UUm4wz0kg8eD77DlPd+fj6iQ1Ad0cmvuVN2v92Yh/fHkWIG5WEKdru0qBKyPLfLZJJ/1Wbims1rtbjsdRB2FNCDooALQjge+Uota7qTVRD9boAHdYmyAn88nhvakrnhY1o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
