env:
  global:
    - secure: Q49h37lRA5S6a++DFyQy6RtfelaZVvC8ELZJKWZBwOxc676uJWRzIMAC4GGa5KKBYORfQ1SSmrtW2CxR3x3ElkgxFnLkugpl7+ihkx5bkgl9vXKPV+3eeA8DtHRn56KMM0lLbmJtzNM7fagini1eeDYsae/z01YrnDZVNzpZozAEdsKqxMXwrJxvshieHY5EmHPo/hJnL8KfNy6E/9RLe0vNphXiysACimHwS8SWZ1blTgVQwes/7wdWVl48aTbt+QpuCticX1HhjcQfCyozbBuGqUD/yGQtEDoJfgiUXfN/71mKX+3xjEQ2YeNBz0VZ2XTgp3YpQVWOzWE6ItmFNS3sA7Pgy4Bz1RuCEM/FTaN6DucNsTcjprzfGU849C2KpDg9wzYNM3vIjiENH44rSJYviSWeYRqaUGwfOpURJKhZw5FtVlDi5qiRBpPqyUUxe4FTlwvbgEXQSMTHHR6oLztAbupTVXdTDOL8lQXQEOJIQUR8X9ZzzpW9DwXjIuncJYgcomR+fjIqZxr3mgw3DDa9GhRU3N9nLcb860XE5hcaev/5F+HwoHwrzq85sqYBShdd7Jkvsg98PLIpGNoBMmVGhWM4nq+q+Dy+YbsgXvk+CDRESS0rdbHaWhoofKVgJt8U2u8Hve6Tj+wWfLKlYs5WA+uZjc+tI5zmejl+2QM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
