env:
  global:
    - secure: c6XVqSCQOYioBzZi7GlisOwKLwALuy2tyDGYclZZGiiS18ic7HnDoDV+cJRvDPNCDWyKxyNYHgWLAvCS4beNBX5iNbDef9L9BTxgzciEVTo57aan1f/SPUcrfojQzJ5WjsXuYSBr2vyD18nB3njOSgxZAmfoQHzwE9KEla9tI3OAsWKAUamhPuwW5Mjo1YLh27BcC7zrrngmYslDywpmFQl199z25yRJ2qQXfOkXAPOLOHoOdzjH96Efsp3c5Ga4dary4yA1wu0vk6HHmtH4bMLR+j5gfNyqpKvuYglWZGNcjqa1kUdiexW2sIYUVT8WQx6Zy/uXdeBZ68y5vaL5vyZEIHKRveLtvP7QpaFPpQ1nTsi2W2iUNDUwZZebIClklfkNuLIm3/0nxCMiAD0ZDKcl5kLPrtq6RD6G26DiN3CPZDyvtDWfSkLpZzaPfzwpZl3jJ9j7G7xYn5dxIbTLXuZ8yohlfsvJH9Tu6sbusPUdzUddXPlCpIhkeScQ2TCjDRAVya+pxZCsgO2bs2hVX5zBZyiDPbogeTqk2jfezO4ywFZp+INjlfkK0jZX7rUOIShV05vMZ9wTE00t4VR5vWIR6BNTl4iDipmPhHgOcfeV2ISKS1mkbHR5Qok+8JcYsVOtT7JhBromp1UtpMOm1KrMrSjv4PQDqFoi1o4JrAI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
