env:
  global:
    - secure: AfWuMjnc+tLIilgXJio0fNB+lVlRPWiyC6uRNK/1LAiddRmfAsNTEHPsDiv8qmNHj9rmefjxLUcfITm9tS890F3Qez4pp8aODNHDN1MmiLbOV3pbthaIAuuzwqtU+M2MgyVclZgeGD7CSIJxGRD1e2E0ZupvAInAE0yJTlppecCPgJuw7SNomN50E3uhFIXJ4NUBL90E8S2qcG/0F8j0uewOap+uEHjfiKXpYvXvagQBjigjLr9bd/RvEUYxARWf1Ujx0I11qn21Ln0CGjegsJG02bVHcxHza6GKBQVsTVg0Wx3fUtBajfHe3YLywQHMtYoWnOuNy1F85G1IFdAOAqFcqOCuV+vOzvH5kWNPk/g+OGH6x+Y+a+q5vDXks41SL5+Q/yD8E42OpRZ/EWsrQ78C9JXc4OCqQIK9COdhsYxX6RGdwZe/x988QZabnAT08QUlakWzto3mnhLCHkUND2Q081fBIM0QPpswpTOjZD2Q7gLi2kR2RF4lRdNozfJ73LTH0VDt4Epb2k6dV7QYXXrQVx3h2QTwOZUV9CLUu45CHdDCDOTO1vqqiySu0TFAo1L4Y/FWLNwdWuv6hJB3iaBbyOtlifcDE82WfmPoZ9PoqQ0WK4VU/YMgZ9aqGu9Z1V+ozRDaLhKE+6OB9DRUzS7qUR3FrkhVE6J3hanNn54=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
