env:
  global:
    - secure: qjHThrSXloLuu8nmzshqok/wSUpxPbrHQ+0j6Cg5qw9qPE6a1+AwuV6r7wr8dDWQlqFdXneoSdqbiPBjzxS8LO8Rn7SDwpu8r+s/mWHD8aSzaBiqQqHarTAy8uUCvl/1sf73xtbSm4DtkUDv5atJsp6ApBXUU7KY3kw1KGP0fBX+2bEtfcPEN0KTaDpO5WCSZmW8vPW1te4DUdJUfmbRVhJDkfV1yr1CHHij1tsphSeO8Nxwfz6uhPH5aZ4cbiwQrIferw/5b85oHlMFmyF4Kp2euywodY7qK84ovbxlYrkV+n/lkYE7dsPJT9WtLc3dRFVbwAQOd6nN9dQybIYa8SuU0EzVOUZ/V0bLwKG9MT1OxE6YDyBbLVs99SinZpgdDzV7v8mcqdAgWNkVbMdbkMKiIPclJ1u0cCAQO3vn/53i5jnIJHTngF2+etYgThlaVXQbARP6CBfNQnYY8UFMUYNL7uaPMhBGpvD6EbIrfFqgLJ/KW9mpCNx5FWTL6PE4qeOXf0xg/cLxIuRuyUTCt3lrnXak5X4fqplrkc84NGLyVcaELOgGBLuOjYagq/TeeeumhP7kV86UShmY1DFOJcHicLinBr/L6AAE9J+btXdzMW17gRyvz2wOtnvC+B/3g4+ESVxmxGjyIvMuyhMeOVnSs0+xBXvaeLeMwNVw4HA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/2o7.net
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
